name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Lint and Audit
        run: |
          npm ci
          npm run lint
          npm audit --production
      - name: Integration test
        run: docker-compose -f docker/docker-compose.yml run tests npm test --force-recreate
